# Generated by Django 3.0.7 on 2020-06-24 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='JobsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, default='category.png', null=True, upload_to='jobs_categories')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobsListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_rate', models.DecimalField(decimal_places=2, default=50.99, max_digits=5)),
                ('description', models.TextField()),
                ('proposals_due_date', models.DateField()),
                ('slug', models.SlugField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('hired', models.BooleanField(default=False)),
                ('proposed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobsReportedIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issue_attachments', verbose_name='Issue Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('hired', 'hired (On Going)'), ('completed', 'completed')], default='hired (On Going)', max_length=11)),
                ('slug', models.SlugField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.DurationModel')),
            ],
        ),
    ]
