# Generated by Django 3.0.7 on 2020-06-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200624_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslistings',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
