# Generated by Django 3.0.7 on 2020-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200628_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobviews',
            name='job',
        ),
        migrations.AddField(
            model_name='jobviews',
            name='job',
            field=models.ManyToManyField(related_name='job', to='jobs.JobsListings'),
        ),
    ]
