# Generated by Django 3.0.7 on 2020-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200628_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobviews',
            name='job',
            field=models.ManyToManyField(related_name='job_views', to='jobs.JobsListings'),
        ),
    ]
