# Generated by Django 3.0.7 on 2020-06-28 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20200628_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobviews',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='jobviews',
            name='freelancer',
            field=models.ManyToManyField(related_name='freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='jobviews',
            name='job',
        ),
        migrations.AddField(
            model_name='jobviews',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.JobsListings'),
        ),
    ]
