# Generated by Django 3.0.7 on 2020-06-28 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_auto_20200628_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobviews',
            name='freelancer',
            field=models.ManyToManyField(related_name='view_freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
