# Generated by Django 3.0.7 on 2020-06-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0008_auto_20200628_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobviews',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='jobviews',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
