# Generated by Django 3.0.7 on 2020-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200628_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='status',
            field=models.CharField(choices=[('hired', 'hired (On Going)'), ('completed', 'completed')], default='hired (On Going)', max_length=20),
        ),
    ]
