# Generated by Django 3.0.7 on 2020-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200624_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
