# Generated by Django 3.0.7 on 2020-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200701_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='featured_image',
            field=models.ImageField(default='article_featured_image.jpg', upload_to='Articles featured images'),
        ),
    ]
