# Generated by Django 3.0.7 on 2020-07-03 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200702_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
