# Generated by Django 3.0.7 on 2020-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200703_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
