# Generated by Django 3.0.7 on 2020-07-03 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_articleviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleviews',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='articleviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
