# Generated by Django 3.0.7 on 2020-07-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200703_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommentsmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.ArticleCommentsModel'),
        ),
    ]
