# Generated by Django 3.0.7 on 2020-07-04 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_replymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='date_replied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
