# Generated by Django 3.0.7 on 2020-06-24 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='Company Name', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, default='company.png', null=True, upload_to='companies')),
                ('banner', models.ImageField(blank=True, default='company.png', null=True, upload_to='company_banners')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('employees', models.CharField(blank=True, choices=[('0-10', '0 - 10'), ('10-20', '10 - 20'), ('20-30', '20 - 30'), ('30-40', '30 - 40'), ('40-50', '40 - 50'), ('50-60', '50 - 60'), ('60-70', '60 - 70'), ('70-80', '70 - 80'), ('80-90', '80 - 90'), ('90-100', '90 - 100')], max_length=10, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.CountryModel')),
            ],
        ),
    ]
