# Generated by Django 3.0.7 on 2020-06-24 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.TextField()),
                ('behaviour', models.BooleanField(default=False)),
                ('quality', models.BooleanField(default=False)),
                ('deadline', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='freelancer_awards')),
                ('award_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, default='freelancer.jpg', upload_to='freelancer_image')),
                ('hire_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('banner', models.ImageField(blank=True, default='freelancer_banner.jpg', null=True, upload_to='freelancer_banners')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='freelancer.png', null=True, upload_to='freelancer_project')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('rate', models.IntegerField()),
                ('all_skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SkillModel')),
            ],
        ),
    ]
