# Generated by Django 3.0.7 on 2020-06-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('freelancer', '0001_initial'),
        ('accounts', '0002_auto_20200624_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerskills',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprojects',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CountryModel'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DepartmentModel'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.GenderModel'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests', to='jobs.JobsCategories'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerexperience',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancereducation',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_education', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerawards',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
